version: "3"
services:
  web:
    image: monkey-benchmark
    build: .
    command: node app.js
    ports:
      - "80:5001"
    restart: always
    depends_on: 
      - "mongo"
    volumes: 
      - .:/myapp
    environment: 
      - MAIL_ADRESS=monkey@baizuo.online
      - MAIL_PASSWORD=Xw#jqfNMgVZQD6!
      - PORT=5001
      - HOST=localhost
  mongo:
    image: mongo

    ports:
      - "27017:27017"
  adminmongo:
    image: "mrvautin/adminmongo"
    ports: 
      - "1234:1234"
    